[package]
name = "chaud"
version = "0.1.0"
authors = ["Christopher Atherton <atherchris@gmail.com>"]
license = "MIT"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cty = "0.2.1"
byteorder = "1.4.2"
